### ISSUE TITLE
Going to try out your dotfiles config

### ISSUE THREAD

**Issue by ar4s-eth** [sagittaros/dotfiles#4]
<- newer dev here.

I'm thinking of trying your dotfiles under a new user account after. I'm assuming that the way you've setup nix here shouldn't interfere with my current user asdf/direnv/homebrew setup?

I tried earlier this year to migrate from homebrew to nix (only as a package manager) and completely botched it... having to start over with a fresh reinstall (this time with dotfiles!)

Very happy to find that you've put in the time to use all of the tools I've been working towards!! 

Small modifications I'll attempt:

- Chemacs2  (before the emacs install step)
- Fish shell (but ZI looks pretty amazing!)

**Comment by inscapist** [comment]
Hello there!

> I'm assuming that the way you've setup nix here shouldn't interfere with my current user asdf/direnv/homebrew setup?

Like you, I am only using Nix as a package manager. The way I did, Nix entirely sits within a separate partition and I only change the PATH variable to bring in the binaries.

Btw, I am no longer using this setup and am thinking of archiving this project. I have migrated to Arch setup.

**Comment by ar4s-eth** [comment]
> The way I did, Nix entirely sits within a separate partition 

Reading about this now, that's actually a relief! Seems like a much safer approach than what I did last time....

>   I have migrated to Arch setup.

I had read about Asahi a couple of weeks ago... welp, there goes the day. lol
